name: Rust Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-13 # get an arm64 machine
    container:
      image: ubuntu:16.04

    steps:
    - name: Test
      run: |
        uname -a
        file /bin/sh

    # - uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: |
    #     apt-get update
    #     apt-get install -y build-essential libusb-1.0-0-dev pkg-config

    # - name: Install Rust
    #   uses: actions-rs/toolchain@v1
    #   with:
    #     profile: minimal
    #     toolchain: stable
    #     override: true

    # - name: Build
    #   run: |
    #     clickable build
    #     find . -name \*.click -exec mv {} . \;

    # - name: Upload
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: flasher
    #     path: "*.click"
